### PR TITLE
Use new Definees for RACK avoidance

### PR DESCRIPTION
**Pull request by baconpaul**
- new ifdef
- cleansup SSE mode also

### CODE REVIEW

**Comment by baconpaul** [comment]
OK @cosinekitty if you pull to head and submodule update should get the new stuff

I'll add a cmake stage to make a zip installer this week and upload it here so people can try the binary. Also thinking a bit about the UI

**Comment by cosinekitty** [comment]
I tried it out and it builds just fine on my system. Cool!

The Elastika UI is pretty basic by VCV Rack standards. The only "weird" thing I do is make the output knob glow when the limiter is active. But that could be changed to an LED lighting up or something, or even skipped for the time being, just to get something working. 

I don't know what kind of artwork capability is supported in a VST plugin. For the VCV Rack version, instead of driving myself twitchy with Inkscape, I wrote a Python script to generate the coordinates for the zig-zag color gradient thing that goes around the sliders. You can take a look at `util/patch_elastika.py` in case that is helpful.

**Comment by baconpaul** [comment]
yeah svg works fine with juce. we use it in surge also.

i almost wrote a UI using your panel directly, actually, but of course you have room for all the cv inputs and attenuverters which we don't need.

**Comment by cosinekitty** [comment]
I don't understand that part about not needing CV inputs and attenuverters. I haven't yet done anything with VST plugins, so maybe you can help me understand that part.

**Comment by baconpaul** [comment]
Every parameter is exposed to the daw for automation by default. So nothing to hook up. If you want to modulate the friction you just modulate the friction using the vst interface in your daw.

**Comment by cosinekitty** [comment]
OK, that makes sense. Is there some way to express what the min, max, and default values are for each parameter?

**Comment by baconpaul** [comment]
> OK, that makes sense. Is there some way to express what the min, max, and default values are for each parameter?

So I coded it so the params are all 0..1 which is a super common pattern. Then you use the to string and from string methods to make the display reasonable and assume modulation is linear

**Comment by baconpaul** [comment]
(I don’t think I did the to and from string hookup in current version)

**Pull request merged**
